### ISSUE TITLE
Hardware powering the robot arm

### ISSUE THREAD

**Issue by dyamon** [OxRAMSociety/RobotArm#1]
## Description

Given the possible shift from a [BCN3D Moveo arm] to a [RBX1 arm] we need to figure out what we need in terms of hardware.

While the design of the two arms is similar, with the main difference being the number of joints (going from 5 to 6), the hardware configuration is quite different:
we are going from a combination of an [Arduino Mega 2560] with a [RAMPS 1.4 shield] (a standard configuration for DIY 3D printers) to a Raspberry Pi with a [SlushEngine Model D 7] (a quite expensive stepper motor driver).

The Moveo arm configuration is not compatible with the RBX1 arm because the RAMPS 1.4 shield is able to control a maximum of 5 stepper motors.

## Details

For the time being we might want to try and stick with the Arduino Mega + RAMPS 1.4 combination (since it's cheaper). This hardware setup currently requires a **12V power source** and can control **up to 5 stepper motors** and a **LCD screen** (which might be useful to display some debugging/status information).
More information on this can be found in the [assembly guide].

The main task is to _find a way to attach a 6th stepper motor to the current setup_.
We might be able to do this with a [stepper expander] or use one of the several way to [add more stepper motor drivers] to the RAMPS 1.4.

Also note that while the picture that shows the hardware configuration for the Moveo arm shows 6 stepper motor drivers, two of them (2nd and 6th from the top) _are connected in parallel_, and hence it's not possible to control them independently.

<p align="center">
  <img src="https://images.squarespace-cdn.com/content/v1/59f79a27d0e628affa90e1ae/1513629516007-4FC2VZBFU7JZXGRJCQ9B/ke17ZwdGBToddI8pDm48kB90nhDVLRdlR5pNUWdwI3V7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0nj1SR5MR8Kya0HFj6EY9V2EuG8Zz1AlhV7HQogQxoPBy4rLX_kCpEpiSn4PcMBN-w/aerial_robot_sketch.png?format=500w">
</p>

There seems to be a way to connect a [Bluetooth module][bluetooth attachment] to the RAMPS shield that would enable wireless communication.

## Roadmap

- [x] Get your hands on some of the hardware.
- [x] Test configuration with 5 stepper motors (according to the [assembly guide]).
- [x] Document previous steps.
- [ ] Blog/social media posts
- [x] Use a stepper extender to connect an additional stepper motor to the configuration.
- [x] *(optional)* test the configuration with a LCD screen and display stepper motor status information.

[BCN3D Moveo arm]: https://www.bcn3d.com/bcn3d-moveo-the-future-of-learning/
[RBX1 arm]: https://roboteurs.com/products/rbx1-remix-3d-printed-6-axis-robot-arm-kit
[Arduino Mega 2560]: https://store.arduino.cc/arduino-mega-2560-rev3
[RAMPS 1.4 shield]: https://reprap.org/wiki/RAMPS_1.4
[SlushEngine Model D 7]: https://roboteurs.com/products/slushengine-model-d
[assembly guide]: https://www.reprap.org/mediawiki/images/0/06/RAMPS_dossier.pdf
[stepper expander]: https://reprap.org/wiki/Stepper_Expander
[add more stepper motor drivers]: https://reprap.org/wiki/Adding_more_extruders
[bluetooth attachment]: https://reprap.org/wiki/RAMPS_1.4#BT_Extension

**Comment by dyamon** [comment]
I bought one of [these kits] from AliExpress.

It contains an **Arduino Mega 2560 R3** (a cheap clone), **RAMPS 1.6** shield, **LCD12864**, 5x **DRV8825 Stepper Motor drivers** compatible with the shield:
- reading the [documentation] for RAMPS 1.4 and 1.6, the two boards should  be compatible.
- compatibility between DRV8825 and stepper motors needs to be tested.
- for the LCD we can use the [u8g2 library] for Arduino to display information about the arm. 

I found a kit with a RAMPS 1.4 but was a bit more expensive considering this one comes with motor drivers as well.

[these kits]: https://www.aliexpress.com/item/4000287477657.html 
[documentation]: https://reprap.org/wiki/RAMPS_1.6
[u8g2 library]: https://github.com/olikraus/u8g2

**Comment by dyamon** [comment]
Additional information on the hardware configuration is provided in the [wiki](https://github.com/OxRAMSociety/RobotArm/wiki/Arduino-and-RAMPS)

**Comment by dyamon** [comment]
We tried to run the 6th motor connecting a [L298N Motor Driver] to the RAMPS 1.4 board without success, both by powering the driver directly from the power supply or by using the 12V *auxiliary fan* pins on the RAMPS.

The driver powers up but the motor stutters back and forth, heating up.
This is most likely due to an excessive amount of current going into the motor or mismatched voltage range between driver and motor.
Using this driver we are not able to control how much current goes into the motor, like with [A4988] motor drivers.

[L298N Motor Driver]: https://www.youtube.com/watch?v=cYTICj4DWYc
[A4988]: https://reprap.org/wiki/A4988

**Comment by dyamon** [comment]
We bought a couple of these [stepper motor extenders](https://www.ebay.co.uk/itm/224643457904).

**Comment by dyamon** [comment]
The circuit is now able to handle 6 stepper motors, thanks to the extension board. The extension board is then connected to the RAMPS 1.4 using some auxiliary pins. More on this in the wiki.

**Comment by dyamon** [comment]
Have a look at [this](https://www.instructables.com/Hacking-Arduino-MegaRAMPS-3D-Printer-Shield-to-Con) for an example on how to use the u8g2 graphic library with the ST12864 display that came with the RAMPS 1.4 kit.
